spring:
  application:
    name: robot
  kafka:
    group-id: robot
    enabled: true
    bootstrap-servers: localhost:9092
    topic:
      producer:
        robot: robotServiceRobot
      consumer:
        round: gameServiceRound
    consumer:
      auto-offset-reset: earliest
